service: whereitsatapi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: krisperssonRegularUser
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::619468094687:role/LambdaAPIGatewayDynamoDB

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getEvents:
    handler: src/functions/getEvents/index.handler
    events:
    - httpApi:
        path: '/api/events'
        method: GET
  orderTicket:
    handler: src/functions/orderTicket/index.handler
    events:
    - httpApi:
        path: '/api/ticket/order'
        method: POST
  verifyTicket:
    handler: src/functions/verifyTicket/index.handler
    events:
    - httpApi:
        path: '/api/ticket/verify'
        method: PUT
  deleteTicket:
    handler: src/functions/deleteTicket/index.handler
    events:
    - httpApi:
        path: '/api/ticket/delete'
        method: DELETE

resources:
    Resources: 
        ticketsDb:
            Type: AWS::DynamoDB::Table
            Properties: 
                TableName: tickets
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
